### ISSUE TITLE
Question: all commands in table format?

### ISSUE THREAD

**Issue by nichatr** [nathanchapman/vscode-javascript-snippets#10]
Is it possible to have all available commands in table format for easier reference?

**Comment by nathanchapman** [comment]
I'll try it out and see if it seems easier to read. I'm only hesitant because of the large code blocks

**Comment by nichatr** [comment]
At last I found out that inside vscode is possible to search for available commands. Pretty handy :-)
Thanks very much for the answer!

**Comment by nathanchapman** [comment]
Mind sharing a screenshot or instructions that helped you?
