### ISSUE TITLE
It breaks default emmet...

### ISSUE THREAD

**Issue by PixelT** [nathanchapman/vscode-javascript-snippets#6]
As in gif below:
https://i.imgur.com/vftPD2y.gifv

**Comment by nathanchapman** [comment]
I'm not sure why that's happening with a PHP file. Might be because it's interpreting emmet HTML and applying this plugin. I've removed the "html" language from the snippets in the newest version of this plugin (0.2.0). Please let me know if it's still broken and feel free to re-open.

**Comment by nathanchapman** [comment]
I actually wasn't able to reproduce this issue pre-0.2.0 either. Let me know if it's still happening, I'm not sure what the underlying cause would be. I did the exact same thing you did in the gif and it works fine.
