### ISSUE TITLE
No semicolons option

### ISSUE THREAD

**Issue by ildukm** [nathanchapman/vscode-javascript-snippets#9]
Hi, can we make an vscode option for no semicolons?
I'm using Standard Style and it's a bit annoying to remove semicolons all the time.
https://standardjs.com/rules.html#semicolons

**Comment by nathanchapman** [comment]
Fixed in [v0.3.2](https://github.com/nathanchapman/vscode-javascript-snippets/commit/d0600a1a67673bd5906d86d51d516aa9360a4187)
